import { AuthProvider } from '@/providers/AuthProvider';
import './globals.css';
import { QueryProvider } from '@/providers/QueryProvider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Poster Generator',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <AuthProvider>
          <body>{children}</body>
        </AuthProvider>
      </QueryProvider>
    </html>
  );
}
